# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3bfaa475a6bde00b1bd599c57f089dc8"
application_url = "https://closes-savings-hans-santa.trycloudflare.com"
embedded = true
name = "Wish-05-test"
handle = "wish-05-test"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers"

[auth]
redirect_urls = [
  "https://closes-savings-hans-santa.trycloudflare.com/auth/callback",
  "https://closes-savings-hans-santa.trycloudflare.com/auth/shopify/callback",
  "https://closes-savings-hans-santa.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "testnewapp12.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
